export default [
  {
    path: "/",
    redirect: "/homepage",
  },
  {
    path: "/auth/login",
    name: "auth",
    component: () => import(`@/views/Auth/Login.vue`),
    meta: { layout: "auth", public: true, auth: false },
  },
  {
    path: "/auth/register",
    name: "register",
    component: () => import(`@/views/Auth/Register.vue`),
    meta: { layout: "auth", public: true, auth: false },
  },
  {
    path: "/auth/forgot-password",
    name: "forgot-password",
    component: () => import(`@/views/Auth/ForgotPassword.vue`),
    meta: { layout: "auth", public: true, auth: false },
  },
  {
    path: "/auth/new-password",
    name: "new-password",
    component: () => import(`@/views/Auth/NewPassword.vue`),
    meta: { layout: "auth", public: true, auth: false },
  },
  {
    path: "/auth/otp",
    name: "otp",
    component: () => import(`@/views/Auth/Otp.vue`),
    meta: { layout: "auth", public: true, auth: false },
  },
  {
    path: "/auth/google",
    name: "google",
    component: () => import(`@/views/Auth/OauthCallback.vue`),
    meta: { layout: "auth", public: true, auth: false },
  },
  {
    path: "/core/user-management",
    name: "user-management",
    component: () => import(`@/views/core/UserManagement/UserManagement.vue`),
    meta: { layout: "dashboard", public: true, auth: false },
  },
  {
    path: "/profile",
    name: "profile",
    component: () => import(`@/views/Profile/Profile.vue`),
    meta: { layout: "dashboard", public: true, auth: false },
  },
  {
    path: "/dashboard",
    name: "dashboard",
    component: () => import("@/views/Dashboard/Dashboard.vue"),
    meta: { layout: "dashboard", auth: true, public: false },
  },
  {
    path: "/core/settings",
    name: "settings",
    component: () => import(`@/views/core/Settings.vue`),
    meta: { layout: "dashboard", public: false, auth: true },
  },
  {
    path: "/core/menus",
    name: "Menus",
    component: () => import("@/views/core/Menu.vue"),
    meta: { layout: "dashboard", public: false, auth: true },
  },
  {
    path: "/core/module",
    name: "Module",
    component: () => import("@/views/core/Module.vue"),
    meta: { layout: "dashboard", public: false, auth: true },
  },
  {
    path: "/:pathMatch(.*)*",
    name: "not-found",
    component: () => import("@/views/NotFound/NotFound.vue"),
    meta: { layout: "auth" },
  },
  {
    path: "/core/content",
    name: "categories-cms",
    component: () => import("@/views/core/categories-cms/CategoriesCms.vue"),
    meta: { layout: "dashboard", public: false, auth: true },
  },
  {
    path: "/core/database",
    name: "database",
    component: () => import("@/views/core/Database.vue"),
    meta: { layout: "dashboard", public: false, auth: true },
  },
  {
    path: "/core/media",
    name: "media",
    component: () => import("@/views/core/Media.vue"),
    meta: { layout: "dashboard", public: false, auth: true },
  },
  {
    path: "/core/repositories",
    name: "repositories",
    component: () => import("@/views/core/Repositories.vue"),
    meta: { layout: "dashboard", public: false, auth: true },
  },
  {
    path: "/core/audit",
    name: "audittrail",
    component: () => import("@/views/core/Audit.vue"),
    meta: { layout: "dashboard", public: false, auth: true },
  },
];
